# development:
#   adapter: postgresql
#   database: sinatra_app
#   username: <%= ENV['PG_USER'] %>
#   password: <%= ENV['PG_PASS'] %>
#   host: localhost
development:
  adapter: sqlite3
  database: dev.db